name: Deno

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
    
      - name: Check formatting
        run: deno fmt --ignore=./npm --check

      - name: Check linter errors
        run: deno lint --ignore=./npm

      - name: Run tests
        run: deno test --ignore=./npm
    